# -*- coding: utf-8 -*-
"""EECS150_ExtraCredit_Project_Code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GgM2N2_fixH0-MQKnlkP0AhOkuKD8hY3
"""

from picamera2 import Picamera2
import cv2
import time
import csv
import numpy as np

#========================================
#1. Define parameters for general camera
#========================================
#Camera Parameters
WIDTH, HEIGHT = 1280, 720 #Resolution
PROC_WIDTH, PROC_HEIGHT = 160, 90 #Lowered Resolution when processing

#Camera Filtering Quality
ALPHA = 0.1 #For low-pass filter

#Light Detection Parameters
BRIGHTNESS_THRESHOLD = 220 #Brightness qualified to be a light
MIN_CONTOUR_AREA = 20

#Video Recording Parameters
VIDEO_FPS = 30
OUTPUT_VIDEO_FILE = "tracking_comparison.avi"
OUTPUT_CSV_FILE = "tracking_data.csv"

#========================================
#2. Set up camera
#========================================
"""
Setup camera with the following parameters:
- Resolution: 1280x720
- Frame Rate: 30 FPS
- Format: RGB888
"""
def setup_camera():
    camera_obj = Picamera2()
    camera_obj.configure(camera_obj.create_video_configuration(
        main = {"size": (WIDTH, HEIGHT), "format": "BGR888"}, #Format in RGB
        controls = {"FrameRate": VIDEO_FPS}
    ))
    camera_obj.start()
    return camera_obj

#========================================
#3. Set up camera recording
#========================================
def setup_video_recording():
    video_obj = cv2.VideoWriter(OUTPUT_VIDEO_FILE, cv2.VideoWriter_fourcc(*"MJPG"), VIDEO_FPS, (WIDTH, HEIGHT))
    video_file = open(OUTPUT_CSV_FILE, "w", newline="", buffering=8192)
    writer_obj = csv.writer(video_file)
    writer_obj.writerow(["timestamp", "raw_x", "raw_y", "filtered_x", "filtered_y", "contour_count"])
    return video_obj, video_file, writer_obj

#========================================
#4. Signal Processing: Identify light and filter
#========================================
#Create a kernel for morphology to clean up noise in the threshold image
cleanup_kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (3, 3)) #Gets rid of blobs smaller than 3x

def detect_light(frame):
    """
    The goal of detect_light is to find the bright light in the frame and return its contours.
    1. Shrink the frame to a smaller size for faster processing.
    2. Convert the frame to grayscale to simplify the image.
    3. Apply a binary threshold to create a mask of bright areas.
    4. Use morphological operations to clean up the mask and remove noise, removes smaller than 3x3 blobs over entire image
    5. Find contours in the cleaned-up mask, which represent the bright blobs.
    6. Return the contours of the bright blobs for further processing.
    """
    downsize_frame = cv2.resize(frame, (PROC_WIDTH, PROC_HEIGHT))
    grayscale_frame = cv2.cvtColor(downsize_frame, cv2.COLOR_BGR2GRAY)
    verify_brightness = cv2.threshold(grayscale_frame, BRIGHTNESS_THRESHOLD, 255, cv2.THRESH_BINARY)[1]
    cleanup_frame = cv2.morphologyEx(verify_brightness, cv2.MORPH_OPEN, cleanup_kernel)
    contour_outline = cv2.findContours(cleanup_frame, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)[0]

    return contour_outline #Returns a list of contours

def find_centroid(contour):
    #Make sure contour exists
    if not contour:
        return None

    max_contour = max(contour, key=cv2.contourArea) #Make sure contour is the largest

    #Make sure contour is large enough
    if cv2.contourArea(max_contour) < MIN_CONTOUR_AREA:
        return None

    #Calculates the area, sum of x positions, and sum of y positions
    #M["m00"] = area of white pixels in contour
    #M["m10"] = sum of X positiions
    #M["m01"] = sum of Y positions
    contour_info = cv2.moments(max_contour)
    cx_center = int(contour_info["m10"]/contour_info["m00"]) #Calculates the x coordinate of the center of the light
    cy_center = int(contour_info["m01"]/contour_info["m00"]) #Calculates the y coordinate of the center of the light

    #Rescale from processing width -> original frame
    cx_center = int(cx_center * (WIDTH / PROC_WIDTH))
    cy_center = int(cy_center * (HEIGHT / PROC_HEIGHT))

    return cx_center, cy_center

def low_pass_filter(cx, cy, prev_cx, prev_cy):
    """
    Applies a low pass filter to the current coordinate based on the previous coordinates
    - Scales by a factor of ALPHA essentially smoothening/averaging out the movement
    - Returns the coordinates at the end
    """
    #For initial case before prev_cx and prev_cy are defined, return the current coordinates
    if prev_cx is None:
        return cx, cy

    filtered_x = ALPHA * cx + (1 - ALPHA) * prev_cx
    filtered_y = ALPHA * cy + (1 - ALPHA) * prev_cy
    return filtered_x, filtered_y

#========================================
#5. Visualization: Draw traces and points on each frame
#========================================
def draw_trace(frame, raw_trace, filtered_trace):
    for i in range(1, (len(raw_trace))):  #Raw trace = red
        cv2.line(frame, raw_trace[i - 1], raw_trace[i], (0, 0, 255), 2)
    for i in range(1, (len(filtered_trace))): #Filtered trace = green
        cv2.line(frame, filtered_trace[i - 1], filtered_trace[i], (0, 255, 0), 2)

def draw_points(frame, cx, cy, filtered_cx, filtered_cy):
    cv2.circle(frame, (cx, cy), 5, (0, 0, 255), -1) #Draws a red circle at the raw coordinate
    cv2.circle(frame, (int(filtered_cx), int(filtered_cy)), 5, (0, 255, 0), -1) #Draws a green circle at the filtered coordinate

#========================================
#Setup for operations
#========================================

#Define variables for main loop
start_time = time.time()

camera_obj = setup_camera()
video_obj, csv_file, csv_writer_obj = setup_video_recording()

filtered_cx, filtered_cy = None, None
raw_trace = []
filtered_trace = []


#Try until output is detected
try:
    while True:
        frame = camera_obj.capture_array() #Capture and creates a NumPy Array that is (720 rows, 1280 cols, 3 rgb)

        # Detect the light and find its center
        contour_list = detect_light(frame)
        centroid = find_centroid(contour_list)

        #If centroid exists, then applies filter
        if centroid:
            cx, cy = centroid #Finds the x, y coordinate of the center of the light

            #Apply our low-pass filter
            filtered_cx, filtered_cy = low_pass_filter(cx, cy, filtered_cx, filtered_cy) #Pass previous coordinate


            #Write our coordinates to CSV file (Time, cx, cy, filtered_cx, filtered_cy)
            csv_writer_obj.writerow([
                round(time.time() - start_time, 4), #Current time - start time
                cx, cy,
                round(filtered_cx, 2), round(filtered_cy, 2),
                len(contour_list)
            ])

            #Updates the trace for video drawing
            raw_trace.append((cx, cy))
            filtered_trace.append((int(filtered_cx), int(filtered_cy)))

            #Make sure you only plot the last 20 points for each to prevent clutter
            raw_trace = raw_trace[-20:]
            filtered_trace = filtered_trace[-20:]

            #Draw traces onto frame
            draw_trace(frame, raw_trace, filtered_trace)
            draw_points(frame, cx, cy, int(filtered_cx), int(filtered_cy))

        #Write video to the disk
        video_obj.write(frame)

except KeyboardInterrupt:
    print("\nFinished recording")
finally:
    #Wrap up operations
    csv_file.close()
    camera_obj.stop()
